import = [
    "~/.config/alacritty/themes/ato-theme.toml"
]

[window]

opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[font]

#normal.family = "ComicMono-Bold"
#bold.family = "ComicMono-Bold"
#italic.family = "JetBrainsMono Font"
#bold_italic.family = "JetBrainsMono Font"

size = 12.0
