# Default colors
[colors.primary]
background = '#2c3640'
foreground = '#bbc2cf'

[colors.normal]
black   = '#282c34'
red     = '#ff6c6b'
green   = '#3a6f30'
yellow  = '#ecbe7b'
blue    = '#51afef'
magenta = '#c678dd'
cyan    = '#46d9ff'
white   = '#bbc2cf'
